export const colors = {
  primary: "#000000",
  buttonText: "#ffffff",
  buttonTextRandom: "#39a4d6",
  buttonCalculate: "#009de0",
  buttonRandom: "#d3edf9",
  buttonHover: "#1fa9e4",
  buttonHoverRandom: "#bfe6f8",
  error: "#d32f2f",
  info: "#eaf9ffff",
  warning: "#ffe3e3ff",
  textSecondary: "#6b6b6b",
  muted: "#6b6b6b",
  border: "#c4c4c4",
  background: "#d3edf9",
  backgroundButtonNavbar: "#85cbe9",
  backgroundNavbar: "#ffffffbb",
  hover: "#6cc5eb",
  low: "#d0f7ffb7",
  good: "#e1ffd0b7",
  high: "#fce2e2b9",
};
